### ISSUE TITLE
Point source warning for ground-failure product

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/earthquake-eventpages#978] opened 2018-05-07 14:14 UTC
I sent in the ground-failure product to dev for the M6.9 Hawaii event:
https://dev01-earthquake.cr.usgs.gov/fdsnws/event/1/query?eventid=us1000dyad&format=geojson
Overall, I think it looks good, but one issue I noticed is that the point source warning showed up even though the product property `rupture-warning` is set to False.

**Comment by llastowka-usgs** [comment] 2018-06-19 19:49
Check for the word false case insensitively.

**Comment by jdbrown-USGS** [comment] 2018-06-22 15:12
I was unable to reproduce this issue. Perhaps it was fixed with an earlier pull request.

**Comment by emthompson-usgs** [comment] 2018-06-25 15:24
@jdbrown-USGS Yes, it is just that the text `(point source)` should be removed if the product property `rupture-warning` is false. I think we actually intended for this to be based on the `point_source` value in info.json, but I think that accessing that value is problematic when making the page and I'm reviewing the product properties now and seeing that `point_source` is not included. So I will add a ticket for us to add that as a product property in the groundfailure repository, but using the `rupture-warning` property will help until we can get that change to take effect.

**Comment by jmfee-usgs** [comment] 2018-06-26 14:30
@emthompson-usgs : not sure if the `(point source)` text is needed at all?  The page currently shows a separate point-source warning when the `rupture-warning` property is set to `False`:

https://github.com/usgs/earthquake-eventpages/blob/master/src/app/ground-failure/ground-failure/ground-failure.component.html#L33

If you can stop by, or take a look at the referenced code above, we can sort out what should be shown and when.

**Comment by emthompson-usgs** [comment] 2018-06-26 16:49
I believe that the original thinking was that we always wanted to have an indication of whether or not the shakemap was based on a point source, which is the motivation for the `(point source)` text. But there would only be a warning with the additional paragraph if it is a point source and the magnitude is above some threshold (~M6 I think). Perhaps @kallstadt-usgs can comment.

**Comment by kallstadt-usgs** [comment] 2018-06-26 18:51
Hi Jeremy, the rupture_warning should show up if rupture_warning = true, not if it is false. rupture_warning is only true if the event is both a point source and above a certain magnitude. So we do need both the (point source) text, which shows up no matter what magnitude, and the warning, which shows up only if the magnitude is above a certain value (at which point rupture_warning is set to true).

**Comment by jmfee-usgs** [comment] 2018-06-26 19:04
@kallstadt-usgs : yes, I mis-spoke earlier but the logic is correct (we only show the warning if it is not "False").

Do you have any thoughts on the `(point source)` portion that appears in the preceding paragraph, which is always shown.  Can we just remove the words `(point source)` from the paragraph that is always shown, and display the separate rupture warning as needed?

**Closed** 2018-06-26 20:50 UTC
Labels: in review
