### ISSUE TITLE
Add recent seismicity layer to interactive map

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-eventpages#245] opened 2015-12-04 20:58 UTC
Options:
- load 7/30 day feed and show all on interactive map
- use specific search parameters (distance/age) and show results on interactive map
- link to latest earthquakes map/list with current earthquake selected (requires support for linking be added to map/list)

**Comment by paulearle** [comment] 2015-12-04 21:20
I can see two main goals for showing earthquakes on the map:

1) Recent seismicity could show the earthquake in relation to an mainshock-aftershock sequence. 
Loading the 7 2.5+  feed is slow on my phone so you might be stuck with a distance/age search. You would want to show the boundaries of the search somehow, maybe a dashed line?.
The link to the latest earthquake map/list would be great for people who could figure out how it works but I think it will confuse the user.

2) Historic seismicity would provide tectonic and seismic backdrop.
I'm guessing this would have to be a bitmap because of the large number of quakes

Paul

**Comment by emartinez-usgs** [comment] 2016-07-07 20:40
Very similar to #558

**Comment by llastowka-usgs** [comment] 2017-07-12 22:06
I think this can be considered a duplicate of 558

**Closed** 2017-07-12 22:06 UTC
Labels: duplicate
