### ISSUE TITLE
Fix "shaking" property error on shakemap pin

### ISSUE THREAD

**Issue by cswilson-usgs** [usgs/earthquake-eventpages#1423] opened 2018-10-15 22:03 UTC
There is an error looking for the "shaking" property of the shakemap pin, which is causing the app to crash

**Comment by dslosky-usgs** [comment] 2018-10-15 23:01
@cbworden This is caused by the same property as #1391. For events with null or '--' maxmmi, what should we display on the shakemap pin? Maybe Shaking Level: Not Felt and Potential Damage: None?

**Comment by cbworden** [comment] 2018-10-16 15:01
Yes, that seems reasonable. These are events that happen in the middle of the ocean, so it's pretty safe to use those descriptions. We are working on revising our system to not produce these events, but we're not there yet.

**Comment by emartinez-usgs** [comment] 2018-10-17 14:45
I think this goes in the right direction, but the shaking impact pipe should be more catch-all ...
```typescript
defaultImpact = {shaking: 'Not felt', damage: 'None'};
mmiImpacts = { /* ... as-is ... */ };

transform(mmi: string): any {
  try {
    impact = mmiImpacts[Math.round(parseFloat(mmi))];
  } catch (e) {
    // Log something ?
    impact = defaultImpact;
  }
  return impact || defaultImpact;
}
```

**Comment by dslosky-usgs** [comment] 2018-10-29 20:16
There's no longer a shaking property on the pin or shakingImpact pipe... I'm gonna close this down. The bubble issue for offshore events is moved to #1467

**Closed by dslosky-usgs** 2018-10-29 20:16 UTC
Labels: RealTimeProducts, scheduled
